apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-node # Should match your K8S_DEPLOYMENT_NAME secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-node
  template:
    metadata:
      labels:
        app: hello-world-node
    spec: 
      serviceAccountName: my-app-ksa # Use the KSA you created/annotated
      containers:
      # Your Application Container
      - name: hello-world-node # Should match your K8S_CONTAINER_NAME secret
        image: moonsol124/hello-world-node:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: db-credentials
        resources:
           requests:
             memory: "128Mi" # Keeping memory request
             cpu: "25m"      # <--- MINIMAL CPU REQUEST
           limits:           # Keeping limits (or adjust if needed)
             memory: "256Mi"
             cpu: "500m"

      # Cloud SQL Auth Proxy Sidecar Container
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.33.9
        command:
          - "/cloud_sql_proxy"
          # --- Make SURE this instance connection name is correct ---
          - "-instances=zinc-epigram-456615-u3:us-central1:test=tcp:1433"
          # Assuming Workload Identity is correctly configured
        securityContext:
           runAsNonRoot: true
           allowPrivilegeEscalation: false
           readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "64Mi" # Keeping memory request
            cpu: "25m"     # <--- MINIMAL CPU REQUEST
          limits:          # Keeping limits (or adjust if needed)
            memory: "128Mi"
            cpu: "250m"
      # Volumes related to SA Key file are commented out assuming Workload Identity